### ISSUE TITLE
cart-item.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [VMaiseyenka/Ang2-N18#3]
Если установить для компонента changeDetection: ChangeDetectionStrategy.OnPush, то при добавлении одного и того же товара, количество в корзине не обновляется. 
Чтобы оно обновлялось надо:
1. или не использовать changeDetection: ChangeDetectionStrategy.OnPush
2. или использовать имутабельные данные, чтобы каждый раз были новые данные
3. или doCheck хук для обновления. 
На мой взгляд, сейчас самым простым способом исправить ситуацию можно с помощью пункта 1.

**Comment by VMaiseyenka** [comment]
Удалено использование ChangeDetectionStrategy для компонента
